RJ/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings
from django.contrib.auth import views as auth_views

from journal.views import (
    index_view,
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
         must_authenticate_view,
)
urlpatterns = [
    # path('', index_view, name="index"),
    path('', include('journal.urls', namespace='journal')),
    path('account/', account_view, name="account"),
    path('admin/', admin.site.urls),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),

    # Reset and Change password
    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journal/urls.py
from django.urls import path, re_path

from . import views

"""Defines URL schemes for users"""

app_name = 'journal'
urlpatterns = [
    path('', views.index_view, name="index"),
    path('research/', views.research_view, name="research"),

    # Research_Section
    # r'^edit_record/(?P<record_id>\d+)/$'
    re_path(r'^research/(?P<topic_id>\d+)/$', views.section_view, name="section"),

    # New_Topic
    path('research/new_topic/', views.new_topic, name="new_topic"),

    # Delete_Topic
    re_path(r'^delete_topic/(?P<topic_id>\d+)/$', views.delete_topic, name="delete_topic"),

    # New_Record
    re_path(r'^research/(?P<topic_id>\d+)/new_record/$', views.new_record, name="new_record"),

    # Edit_Record
    re_path(r'^edit_record/(?P<record_id>\d+)/$', views.edit_record, name="edit_record"),

    # Delete_Record
    re_path(r'^delete_record/(?P<record_id>\d+)/$', views.delete_record, name="delete_record"),
]

journal/models.py
from django.conf import settings
from django.db import models


class Topic(models.Model):
    """New research section"""
    text = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Returns the stream representation of the model"""
        return self.text

    class Meta:
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'


class Record(models.Model):
    """"New record"""

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    title = models.CharField(max_length=100,  verbose_name='Заголовок')
    comment = models.CharField(max_length=10000, blank=True, verbose_name='Описание')
    file = models.FileField(default='default.png', blank=True, null=True, verbose_name='Файл')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Автор')

    date_added = models.DateTimeField(auto_now=True, verbose_name='Дата')

    def __str__(self):
        """Returns the stream representation of the model"""
        return self.title

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

journal/forms.py
from django.forms import ModelForm, Textarea
from .models import Topic, Record
from django.utils.translation import gettext_lazy as _


class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields = ['text']


class RecordForm(ModelForm):
    class Meta:
        model = Record
        fields = ['title', 'comment', 'file']

        widgets = {
            'comment': Textarea(attrs={'cols': 80, 'rows': 2}),
        }

journal/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import TopicForm, RecordForm
from .models import Topic, Record
from account.models import Account


def index_view(request):
    """Home page of RJ app"""
    return render(request, 'journal/index.html')


def research_view(request):
    """Displays a list of research topics"""
    context = {}
    topics = Topic.objects.all()
    context['topics'] = topics
    if request.method != 'POST':
        form = TopicForm
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('journal:research'))
    context['form'] = form
    return render(request, 'journal/research.html', context)


def section_view(request, topic_id):
    context = {}
    topic = Topic.objects.get(id=topic_id)
    records = topic.record_set.order_by('-date_added')
    context['topic'] = topic
    context['records'] = records
    return render(request, 'journal/section.html', context)


def new_topic(request):
    """Adding a new topic"""
    if request.method != 'POST':
        form = TopicForm
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('journal:research'))
    context = {'form': form}
    return render(request, 'journal/new_topic.html', context)


def delete_topic(request, topic_id):
    """Delete record"""
    topic = Topic.objects.get(id=topic_id)
    topic.delete()
    return HttpResponseRedirect(reverse('journal:research'))


def new_record(request, topic_id):
    """Adding a new record"""
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    form = RecordForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        topic = Topic.objects.get(id=topic_id)
        obj.author = author
        obj.topic = topic
        obj.save()
        form = RecordForm()
        return redirect('journal:research')

    context['form'] = form
    return render(request, 'journal/new_record.html', context)


def edit_record(request, record_id):
    """Edits an existing record"""
    record = Record.objects.get(id=record_id)

    if request.method != 'POST':
        # Original request; the form is filled with the data of the current record
        form = RecordForm(instance=record)
    else:
        # Sending POST data; process data
        form = RecordForm(instance=record, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('journal:research'))

    context = {'record': record, 'form': form}
    return render(request, 'journal/edit_record.html', context)


def delete_record(request, record_id):
    """Delete record"""
    record = Record.objects.get(id=record_id)
    record.delete()
    return HttpResponseRedirect(reverse('journal:research'))

journal/templates/snippets/footer.html
<!-- FOOTER -->
<hr>
<div class="d-flex flex-row align-items-center footer">
  <p class="m-auto">Rocket Journal | 2020</p>
</div>
<!-- END FOOTER -->

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

journal/templates/snippets/header.html
  {% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link rel="stylesheet" href="{% static "style.css" %}">

<!-- HEADER -->
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">
    <a class="blog-header-logo text-dark">Rocket Journal</a>
    {% if request.user.is_authenticated %}
    <a class="p-1 text-dark"> Привет, {{  request.user.username }}</a>
    {% endif %}
  </h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="{% url 'journal:index' %}">Главная</a>
    {% if request.user.is_authenticated %}
      <a class="p-2 text-dark" href="{% url 'journal:research' %}">Испытания</a>
      <a class="p-2 text-dark" href="{% url 'account' %}">Профиль</a>
      <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
    {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a>
      <a class="btn btn-outline-primary" href="{% url 'register' %}">Регистрация</a>
    {% endif %}
  </nav>
</div>
<!-- END HEADER -->