RJ/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings
from django.contrib.auth import views as auth_views

from journal.views import (
    index_view,
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
         must_authenticate_view,
)
urlpatterns = [
    # path('', index_view, name="index"),
    path('', include('journal.urls', namespace='journal')),
    path('account/', account_view, name="account"),
    path('admin/', admin.site.urls),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),

    # Reset and Change password
    path('password_change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journal/urls.py
from django.urls import path, re_path

from . import views

"""Defines URL schemes for users"""

app_name = 'journal'
urlpatterns = [
    path('', views.index_view, name="index"),
    path('research/', views.research_view, name="research"),

    # Research_Section
    # r'^edit_record/(?P<record_id>\d+)/$'
    re_path(r'^research/(?P<topic_id>\d+)/$', views.section_view, name="section"),

    # New_Topic
    path('research/new_topic/', views.new_topic, name="new_topic"),

    # Delete_Topic
    re_path(r'^delete_topic/(?P<topic_id>\d+)/$', views.delete_topic, name="delete_topic"),

    # New_Record
    re_path(r'^research/(?P<topic_id>\d+)/new_record/$', views.new_record, name="new_record"),

    # Edit_Record
    re_path(r'^edit_record/(?P<record_id>\d+)/$', views.edit_record, name="edit_record"),

    # Delete_Record
    re_path(r'^delete_record/(?P<record_id>\d+)/$', views.delete_record, name="delete_record"),
]

journal/models.py
from django.conf import settings
from django.db import models


class Topic(models.Model):
    """New research section"""
    text = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Returns the stream representation of the model"""
        return self.text

    class Meta:
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'


class Record(models.Model):
    """"New record"""

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    title = models.CharField(max_length=100,  verbose_name='Заголовок')
    comment = models.CharField(max_length=10000, blank=True, verbose_name='Описание')
    file = models.FileField(default='default.png', blank=True, null=True, verbose_name='Файл')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Автор')

    date_added = models.DateTimeField(auto_now=True, verbose_name='Дата')

    def __str__(self):
        """Returns the stream representation of the model"""
        return self.title

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

journal/forms.py
from django.forms import ModelForm, Textarea
from .models import Topic, Record
from django.utils.translation import gettext_lazy as _


class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields = ['text']


class RecordForm(ModelForm):
    class Meta:
        model = Record
        fields = ['title', 'comment', 'file']

        widgets = {
            'comment': Textarea(attrs={'cols': 80, 'rows': 2}),
        }

journal/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import TopicForm, RecordForm
from .models import Topic, Record
from account.models import Account


def index_view(request):
    """Home page of RJ app"""
    return render(request, 'journal/index.html')


def research_view(request):
    """Displays a list of research topics"""
    context = {}
    topics = Topic.objects.all()
    context['topics'] = topics
    if request.method != 'POST':
        form = TopicForm
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('journal:research'))
    context['form'] = form
    return render(request, 'journal/research.html', context)


def section_view(request, topic_id):
    context = {}
    topic = Topic.objects.get(id=topic_id)
    records = topic.record_set.order_by('-date_added')
    context['topic'] = topic
    context['records'] = records
    return render(request, 'journal/section.html', context)


def new_topic(request):
    """Adding a new topic"""
    if request.method != 'POST':
        form = TopicForm
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('journal:research'))
    context = {'form': form}
    return render(request, 'journal/new_topic.html', context)


def delete_topic(request, topic_id):
    """Delete record"""
    topic = Topic.objects.get(id=topic_id)
    topic.delete()
    return HttpResponseRedirect(reverse('journal:research'))


def new_record(request, topic_id):
    """Adding a new record"""
    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    form = RecordForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=user.email).first()
        topic = Topic.objects.get(id=topic_id)
        obj.author = author
        obj.topic = topic
        obj.save()
        form = RecordForm()
        return redirect('journal:research')

    context['form'] = form
    return render(request, 'journal/new_record.html', context)


def edit_record(request, record_id):
    """Edits an existing record"""
    record = Record.objects.get(id=record_id)

    if request.method != 'POST':
        # Original request; the form is filled with the data of the current record
        form = RecordForm(instance=record)
    else:
        # Sending POST data; process data
        form = RecordForm(instance=record, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('journal:research'))

    context = {'record': record, 'form': form}
    return render(request, 'journal/edit_record.html', context)


def delete_record(request, record_id):
    """Delete record"""
    record = Record.objects.get(id=record_id)
    record.delete()
    return HttpResponseRedirect(reverse('journal:research'))

journal/templates/journal/edit_record.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="flex-row p-2 mb-2">
    <h4 class="flex-grow-1 ">Редактирование записи:</h4>
  </div>
  <div class="container">
    <div class="row">
        <div class="col-lg-10 offset-lg-1">
            <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

                <!-- title -->
                <div class="form-group">
                    <label for="id_title">Заголовок</label>
                    <input class="form-control" type="text" name="title" id="id_title" placeholder="Заголовок" required
                           value="{{ form.initial.title }}">
                </div>

                <!-- Body -->
                <div class="form-group">
                    <label for="id_comment">Описание</label>
                    <textarea class="form-control" rows="10" type="text" name="comment" id="id_comment"
                              placeholder="Добавьте комментарий" autofocus>{{ form.initial.comment }}</textarea>
                </div>

                <!-- File -->
                <div class="form-group custom-file mb-2">
                    <label class="custom-file-label" for="customFile">Выберите файл</label>
                    <input type="file" name="file" class="custom-file-input" id="customFile" value="{{ form.initial.file }}">
                </div>


                <!-- Submit btn -->
                <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Сохранить</button>
            </form>
        </div>
    </div>

  </div>
</div>



{% endblock content %}

journal/templates/journal/index.html
{% extends "base.html" %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Rocket Journal</h1>
  <p class="lead">Электронный журнал для ведения исследовательской деятельности!
  </p>
</div>
<p></p>

{% endblock content %}

journal/templates/journal/new_record.html
{% extends "base.html" %}

{% block content %}
<div class="container">
<div class="flex-row p-2 my-2">
    <h4 class="flex-grow-1 ">Добавить новую запись:</h4>
  </div>
<div class="container">
    <div class="row">
        <div class="col-lg-10 offset-lg-1">
            <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

                <!-- title -->
                <div class="form-group">
                    <label for="id_title">Заголовок</label>
                    <input class="form-control" type="text" name="title" id="id_title" placeholder="Заголовок" required autofocus>
                </div>

                <!-- Body -->
                <div class="form-group">
                    <label for="id_comment">Описание</label>
                    <textarea class="form-control" rows="10" type="text" name="comment" id="id_comment" placeholder="Добавьте комментарий"></textarea>
                </div>

                <!-- File -->
                <div class="form-group custom-file mb-2">
                    <label class="custom-file-label" for="customFile">Выберите файл</label>
                    <input type="file" name="file" class="custom-file-input" id="customFile">
                </div>


                <!-- Submit btn -->
                <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Сохранить</button>
            </form>
        </div>
    </div>
</div>
</div>

{% endblock content %}

journal/templates/journal/new_topic.html
{% extends "journal/research.html" %}

{% block content %}
<form class="form-row" method="post">{% csrf_token %}
  <p class="lead">Добавить испытание</p>
  <div class="col">
      <input type="text" name="text" id="inputTopic"  class="form-control" required autofocus>
  </div>

  <button class="btn btn-lg btn-primary btn-block" type="submit">Продолжить</button>
</form>

{% endblock content %}

journal/templates/journal/research.html
{% extends "base.html" %}

{% block content %}
<div class="container">

    <div class="d-flex justify-content-end my-2 my-md-0 align-items-center p-3 px-md-4 mb-3">
      <form class="form-row" method="post">{% csrf_token %}
        <h1 class="py-2 mt-2 mr-2 lead">Добавить испытание</h1>
        <div class="py-2 mr-2 col">
          <input type="text" name="text" id="inputTopic"  class="form-control" required>
        </div>
        <button class="btn btn btn-outline-success my-2" type="submit">Добавить</button>
      </form>
    </div>

</div>

<div class="pricing-header px-3 py-3 py-md-3 mx-auto text-center  ">
  <h1 class="display-4">Испытания</h1>

  <div class="card-deck d-flex flex-column p-2 mb-3 text-left ">
    {% for topic in topics %}
      <div class="card flex-row p-2 mb-2 lead shadow-sm">
        <a class="text-decoration-none clip flex-grow-1" href="{% url 'journal:section' topic.id %}">
          {{ topic.date_added|date:"M d, Y" }} : {{ topic }}</a>
        <a href="{% url 'journal:delete_topic' topic.id %}" title="Удалить">
          <svg class="bi bi-x text-danger mb-1" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z"/>
            <path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z"/>
          </svg>
        </a>
      </div>
    {% empty %}
      <div class="card p-2 lead shadow-sm">Ни одной записи ещё не было добавлено.</div>
    {% endfor %}
  </div>

</div>

{% endblock content %}

journal/templates/journal/section.html
{% extends "base.html" %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-left">
  <div class="card flex-row p-2 mb-2 lead">
    <h1 class="clip flex-grow-1">Испытание: {{ topic }}</h1>
    <a class="btn btn-outline-secondary my-2" href="{% url 'journal:new_record' topic.id %}">Добавить запись</a>
  </div>
  <div class="d-flex flex-column p-2 mb-3">
        {% for record in records %}
        <div class="card flex-row p-2 mb-2 lead shadow-sm">
            <div class="flex-column flex-grow-1">
            <p class="lead ">{{ record.date_added|date:"M d, Y" }} : {{ record }} </p>
            <p>{{ record.file }}</p>
            <p>{{ record.comment }}</p>
            </div>
            <div class="flex-column">
                <a class="text-decoration-none" href="{% url 'journal:edit_record' record.id %}">
                    <svg class="bi bi-pencil text-info" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M11.293 1.293a1 1 0 0 1 1.414 0l2 2a1 1 0 0 1 0 1.414l-9 9a1 1 0 0 1-.39.242l-3 1a1 1 0 0 1-1.266-1.265l1-3a1 1 0 0 1 .242-.391l9-9zM12 2l2 2-9 9-3 1 1-3 9-9z"/>
                      <path fill-rule="evenodd" d="M12.146 6.354l-2.5-2.5.708-.708 2.5 2.5-.707.708zM3 10v.5a.5.5 0 0 0 .5.5H4v.5a.5.5 0 0 0 .5.5H5v.5a.5.5 0 0 0 .5.5H6v-1.5a.5.5 0 0 0-.5-.5H5v-.5a.5.5 0 0 0-.5-.5H3z"/>
                    </svg>
                </a>
                <a href="{% url 'journal:delete_record' record.id %}">
                    <svg class="bi bi-x text-danger" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z"/>
                      <path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z"/>
                    </svg>
                </a>
            </div>
        </div>
        {% empty %}
            <p class="lead">Ни одной записи ещё не было добавлено.</p>
        {% endfor %}
  </div>
</div>
<p></p>

{% endblock content %}